"""New table Status, new field - Article.status

Revision ID: 115f1aecec18
Revises: d7b5dbe4a567
Create Date: 2022-07-11 18:51:28.867730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115f1aecec18'
down_revision = 'd7b5dbe4a567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=True),
    sa.Column('ulm', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ulm'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sqlite_stat1')
    op.drop_table('sqlite_stat4')
    op.drop_table('temp')
    op.add_column('article', sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'status')
    op.create_table('temp',
    sa.Column('fs01', sa.TEXT(), nullable=True),
    sa.Column('fi01', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('fi01')
    )
    op.create_table('sqlite_stat4',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('neq', sa.NullType(), nullable=True),
    sa.Column('nlt', sa.NullType(), nullable=True),
    sa.Column('ndlt', sa.NullType(), nullable=True),
    sa.Column('sample', sa.NullType(), nullable=True)
    )
    op.create_table('sqlite_stat1',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('stat', sa.NullType(), nullable=True)
    )
    op.drop_table('status')
    # ### end Alembic commands ###
