"""Add ArticleRating table. Alter table User: add user_hash

Revision ID: e1dc0988e2dc
Revises: 47a5bec61d82
Create Date: 2022-08-05 14:14:00.263210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1dc0988e2dc'
down_revision = '47a5bec61d82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sqlite_stat4')
    op.drop_table('sqlite_stat1')
    op.alter_column('article', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('user_hash', sa.String(length=254), nullable=True))
    op.create_foreign_key(None, 'user', 'userrole', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user', 'user', ['ulm'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_hash')
    op.alter_column('article', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('sqlite_stat1',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('stat', sa.NullType(), nullable=True)
    )
    op.create_table('sqlite_stat4',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('neq', sa.NullType(), nullable=True),
    sa.Column('nlt', sa.NullType(), nullable=True),
    sa.Column('ndlt', sa.NullType(), nullable=True),
    sa.Column('sample', sa.NullType(), nullable=True)
    )
    op.drop_table('article_rating')
    # ### end Alembic commands ###
