"""New class Status. New field Article.status

Revision ID: 917fd73fdc58
Revises: d7b5dbe4a567
Create Date: 2022-07-08 13:08:02.879249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917fd73fdc58'
down_revision = 'd7b5dbe4a567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_stat1')
    op.drop_table('article')
    op.drop_table('userrole')
    op.drop_table('user')
    op.drop_table('sqlite_stat4')
    op.drop_table('temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp',
    sa.Column('fs01', sa.TEXT(), nullable=True),
    sa.Column('fi01', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('fi01')
    )
    op.create_table('sqlite_stat4',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('neq', sa.NullType(), nullable=True),
    sa.Column('nlt', sa.NullType(), nullable=True),
    sa.Column('ndlt', sa.NullType(), nullable=True),
    sa.Column('sample', sa.NullType(), nullable=True)
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('passwd', sa.VARCHAR(length=254), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('register_date', sa.DATETIME(), nullable=True),
    sa.Column('dlm', sa.DATETIME(), nullable=True),
    sa.Column('ulm', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('userrole',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rolename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ulm', sa.INTEGER(), nullable=True),
    sa.Column('dlm', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['ulm'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rolename')
    )
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('intro', sa.VARCHAR(length=300), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('dlm', sa.DATETIME(), nullable=True),
    sa.Column('creation_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqlite_stat1',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('stat', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
